### ISSUE TITLE
orientationchange cause cutted screen

### ISSUE THREAD

**Issue by daorithos** [jolicode/Badass-Pageflow#7]
When the orientation of device change, the effect is this:
![badass](https://f.cloud.github.com/assets/6977228/2438300/167f1b44-adf0-11e3-9c86-852e08bd9a55.jpg)
have a solution?
Thanks

**Comment by xavierlacot** [comment]
A PR is on the go: https://github.com/jolicode/Badass-Pageflow/pull/9
